### ISSUE TITLE
Implement tokio-dbus

### ISSUE THREAD

**Issue by IniterWorker** [zibebe/networkmanager-rs#5]
We should focus on Async-first,

Async support in Rust has become a first class citizen and it's about time to use it.
While many things here do not require async right now, it will help with the Sync and the Send (not currently supported).

- https://github.com/diwic/dbus-rs
- https://crates.io/crates/dbus-async,

What do you think @he4d?

**Comment by he4d** [comment]
@IniterWorker 

I would rather go with that one as it depends on the same dbus crate as we use here:

https://crates.io/crates/dbus-tokio/

**Comment by yavko** [comment]
Wouldn't it be better to use the official zbus crate instead which is developed by freedesktop, which has async
